apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: router-service
  app.kubernetes.io/component: routing
  app.kubernetes.io/part-of: chat4all

namePrefix: ""
namespace: default
