apiVersion: v1
kind: Service
metadata:
  name: telegram-connector
  labels:
    app: telegram-connector
    component: connector
spec:
  type: ClusterIP
  selector:
    app: telegram-connector
  ports:
  - name: http
    port: 8092
    targetPort: 8092
    protocol: TCP
