apiVersion: v1
kind: Service
metadata:
  name: instagram-connector
  labels:
    app: instagram-connector
    component: connector
spec:
  type: ClusterIP
  selector:
    app: instagram-connector
  ports:
  - name: http
    port: 8093
    targetPort: 8093
    protocol: TCP
